### ISSUE TITLE
Update geometries  to geojson

### ISSUE THREAD

**Issue by simnh** [ZNES-datapackages/Status-quo-2015#1]

**Comment by s3pp** [comment]
Containing a non-tabular resource the resulting datapackage profile shouldn't be `tabular-data-package`, I guess.
https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/package.py#L208-L208

**Comment by s3pp** [comment]
Unfortunately this is not a very nice, hackish solution to the problem. As a consequence we will stick with the geometries in csv file format for now. Maybe the required geometries can be included via an external datapackage containing geodata in geojson format.

**Comment by s3pp** [comment]
Geometries for buses and for dispatchable powerplants are included in geojson format.
